name: Actualizar GPKG desde QFieldCloud

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 20 * * 1'
  workflow_dispatch:
  
jobs:
  actualizar-gpkg:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Instalar dependencias
        run: |
          pip install geopandas qfieldcloud-sdk pandas pytz 

      - name: Crear carpeta de salida
        run: mkdir -p output

      - name: Ejecutar script principal
        run: python main.py
        env:
          QFIELD_USER: ${{ secrets.QFIELD_USER }}
          QFIELD_PASS: ${{ secrets.QFIELD_PASS }}
          QFIELD_PROJECT_ID: ${{ secrets.QFIELD_PROJECT_ID }}
